// Token build: DTCG JSON in src/ -> CSS custom properties, flat JSON, and Swift.
//
// Style Dictionary handles parsing, alias resolution and the CSS output. The
// Swift files are emitted by hand from the resolved token trees so that light
// and dark values for one semantic token land in a single declaration.
//
// Run with `npm run build:tokens` from the repo root.

import StyleDictionary from 'style-dictionary';
import { formattedVariables } from 'style-dictionary/utils';
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..', '..');
const config = JSON.parse(await readFile(path.join(repoRoot, 'ds.config.json'), 'utf8'));

const DIST = path.join(here, 'dist');
const SWIFT_DIR = path.join(repoRoot, 'Sources', config.swift.module, 'Generated');
const HEADER = `Generated by @${config.name}/tokens (packages/tokens/build.mjs). Do not edit by hand.`;

// Which top-level token groups are sized in rem on the web (everything else
// dimension-typed stays in px).
const REM_GROUPS = new Set(['space', 'font']);
const ROOT_FONT_PX = 16;

const isSemantic = (token) => token.filePath.includes(`${path.sep}semantic${path.sep}`);
const pxToNumber = (value) => {
  const n = parseFloat(String(value).replace(/px$/, ''));
  if (Number.isNaN(n)) throw new Error(`Expected a px dimension, got "${value}"`);
  return n;
};

// ---------------------------------------------------------------------------
// Transforms (CSS only)
// ---------------------------------------------------------------------------

StyleDictionary.registerTransform({
  name: 'ds/dimension/css',
  type: 'value',
  filter: (token) => token.$type === 'dimension',
  transform: (token) => {
    const px = pxToNumber(token.$value);
    return REM_GROUPS.has(token.path[0]) ? `${px / ROOT_FONT_PX}rem` : `${px}px`;
  },
});

StyleDictionary.registerTransform({
  name: 'ds/fontFamily/css',
  type: 'value',
  filter: (token) => token.$type === 'fontFamily',
  transform: (token) => {
    const families = Array.isArray(token.$value) ? token.$value : [token.$value];
    return families.map((f) => (/[\s-]/.test(f) ? `"${f}"` : f)).join(', ');
  },
});

StyleDictionary.registerTransform({
  name: 'ds/cubicBezier/css',
  type: 'value',
  filter: (token) => token.$type === 'cubicBezier',
  transform: (token) => `cubic-bezier(${token.$value.join(', ')})`,
});

const CSS_TRANSFORMS = [
  'name/kebab',
  'ds/dimension/css',
  'ds/fontFamily/css',
  'ds/cubicBezier/css',
];

// ---------------------------------------------------------------------------
// Formats
// ---------------------------------------------------------------------------

// Emits one block of declarations. The build below stitches several of these
// into a single tokens.css so the light and dark builds share one file.
StyleDictionary.registerFormat({
  name: 'ds/css-block',
  format: ({ dictionary, options }) =>
    formattedVariables({
      format: 'css',
      dictionary,
      outputReferences: options.outputReferences,
      usesDtcg: true,
    }),
});

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

function makeDictionary(mode) {
  return new StyleDictionary({
    source: [path.join(here, 'src/core/*.json'), path.join(here, `src/semantic/${mode}.json`)],
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transforms: CSS_TRANSFORMS,
        prefix: config.cssPrefix || undefined,
        files: [
          {
            destination: `_${mode}.css`,
            format: 'ds/css-block',
            options: { outputReferences: true },
            // Core tokens live in the light build only; the dark block carries
            // just the semantic overrides.
            filter: mode === 'light' ? undefined : (token) => isSemantic(token),
          },
        ],
      },
      // No transforms: resolved raw values, used for JSON and Swift.
      raw: { transforms: [] },
    },
  });
}

const light = makeDictionary('light');
const dark = makeDictionary('dark');

// -- CSS --------------------------------------------------------------------

async function cssBlock(sd) {
  const { platformConfig, dictionary } = await sd.getPlatform('css');
  const { output } = await sd.formatFile(platformConfig.files[0], platformConfig, dictionary);
  return output;
}
const lightCss = await cssBlock(light);
const darkCss = await cssBlock(dark);

// formattedVariables already indents each line by two spaces.
const nested = (block) => block.trimEnd().replace(/^/gm, '  ');
const cssOut = `/* ${HEADER} */

:root {
${lightCss.trimEnd()}
}

[data-theme='dark'] {
${darkCss.trimEnd()}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${nested(darkCss)}
  }
}
`;

await mkdir(path.join(DIST, 'css'), { recursive: true });
await writeFile(path.join(DIST, 'css', 'tokens.css'), cssOut);

// -- Resolved trees (raw values) --------------------------------------------

const lightTokens = flatten(await light.exportPlatform('raw'));
const darkTokens = flatten(await dark.exportPlatform('raw'));

function flatten(tree, prefix = [], out = []) {
  for (const [key, value] of Object.entries(tree)) {
    if (key.startsWith('$')) continue;
    if (value && typeof value === 'object' && '$value' in value) {
      out.push({
        path: [...prefix, key],
        $type: value.$type,
        $value: value.$value,
        $description: value.$description,
        semantic: isSemantic(value),
      });
    } else if (value && typeof value === 'object') {
      flatten(value, [...prefix, key], out);
    }
  }
  return out;
}

// -- JSON -------------------------------------------------------------------

const jsonOut = { $comment: HEADER, core: {}, light: {}, dark: {} };
for (const t of lightTokens) {
  const bucket = t.semantic ? jsonOut.light : jsonOut.core;
  bucket[t.path.join('.')] = { $type: t.$type, $value: t.$value };
}
for (const t of darkTokens.filter((t) => t.semantic)) {
  jsonOut.dark[t.path.join('.')] = { $type: t.$type, $value: t.$value };
}
await mkdir(path.join(DIST, 'json'), { recursive: true });
await writeFile(path.join(DIST, 'json', 'tokens.json'), JSON.stringify(jsonOut, null, 2) + '\n');

// -- Swift ------------------------------------------------------------------

const SWIFT_KEYWORDS = new Set([
  'class',
  'default',
  'enum',
  'extension',
  'func',
  'import',
  'init',
  'let',
  'protocol',
  'static',
  'struct',
  'var',
  'true',
  'false',
  'nil',
  'self',
  'Self',
  'Type',
  'in',
  'is',
  'as',
  'do',
  'if',
  'else',
  'for',
  'while',
  'return',
  'switch',
  'case',
  'break',
  'continue',
  'operator',
  'private',
  'public',
  'internal',
  'open',
  'where',
  'throw',
  'throws',
  'try',
  'catch',
  'defer',
  'guard',
]);

const camel = (s) => s.replace(/[-_\s]+(.)/g, (_, c) => c.toUpperCase());
const pascal = (s) => {
  const c = camel(s);
  return c.charAt(0).toUpperCase() + c.slice(1);
};
// Leaf identifier: camelCase, digits get an `n` prefix, keywords are backticked.
const swiftIdent = (s) => {
  let id = camel(s);
  if (/^\d/.test(id)) id = `n${id}`;
  return SWIFT_KEYWORDS.has(id) ? `\`${id}\`` : id;
};
const swiftEnumName = (s) => {
  let id = pascal(s);
  if (/^\d/.test(id)) id = `N${id}`;
  return id;
};

// Top-level token group -> Swift file / enum.
const SWIFT_GROUPS = {
  color: { enum: 'Color', file: 'Tokens+Color.swift' },
  space: { enum: 'Space', file: 'Tokens+Space.swift' },
  radius: { enum: 'Radius', file: 'Tokens+Radius.swift' },
  font: { enum: 'Typography', file: 'Tokens+Typography.swift' },
  duration: { enum: 'Motion', file: 'Tokens+Motion.swift', sub: 'Duration' },
  ease: { enum: 'Motion', file: 'Tokens+Motion.swift', sub: 'Ease' },
  z: { enum: 'ZIndex', file: 'Tokens+ZIndex.swift' },
};

const darkByPath = new Map(darkTokens.map((t) => [t.path.join('.'), t]));

function swiftValue(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'color': {
      // Fully qualified: the generated `enum Color` shadows SwiftUI.Color inside the namespace.
      if (!token.semantic) return { type: 'SwiftUI.Color', expr: `SwiftUI.Color(hex: "${v}")` };
      const d = darkByPath.get(token.path.join('.'));
      return {
        type: 'SwiftUI.Color',
        expr: `SwiftUI.Color(light: "${v}", dark: "${d ? d.$value : v}")`,
      };
    }
    case 'dimension':
      return { type: 'CGFloat', expr: String(pxToNumber(v)) };
    case 'number':
      return { type: 'Double', expr: String(v) };
    case 'fontWeight':
      return { type: 'SwiftUI.Font.Weight', expr: fontWeight(v) };
    case 'fontFamily': {
      const list = Array.isArray(v) ? v : [v];
      return {
        type: 'FontFamily',
        expr: `FontFamily(${list.map((f) => JSON.stringify(f)).join(', ')})`,
      };
    }
    case 'duration': {
      const ms = parseFloat(String(v).replace(/ms$/, ''));
      return { type: 'TimeInterval', expr: String(ms / 1000) };
    }
    case 'cubicBezier': {
      const [x1, y1, x2, y2] = v;
      return {
        type: 'SwiftUI.UnitCurve',
        expr: `SwiftUI.UnitCurve.bezier(startControlPoint: UnitPoint(x: ${x1}, y: ${y1}), endControlPoint: UnitPoint(x: ${x2}, y: ${y2}))`,
      };
    }
    default:
      throw new Error(
        `No Swift mapping for token type "${token.$type}" at ${token.path.join('.')}`,
      );
  }
}

function fontWeight(w) {
  const map = {
    100: '.ultraLight',
    200: '.thin',
    300: '.light',
    400: '.regular',
    500: '.medium',
    600: '.semibold',
    700: '.bold',
    800: '.heavy',
    900: '.black',
  };
  const key = Math.round(Number(w) / 100) * 100;
  return map[key] ?? '.regular';
}

// Build nested enum trees per file.
const files = new Map(); // file -> { enum, tree }
for (const t of lightTokens) {
  const group = SWIFT_GROUPS[t.path[0]];
  if (!group)
    throw new Error(`Unknown top-level token group "${t.path[0]}" — add it to SWIFT_GROUPS`);
  if (!files.has(group.file)) files.set(group.file, { enum: group.enum, tree: {} });
  const segments = [...(group.sub ? [group.sub] : []), ...t.path.slice(1)];
  let node = files.get(group.file).tree;
  for (const seg of segments.slice(0, -1)) {
    node[seg] ??= {};
    node = node[seg];
  }
  node[segments.at(-1)] = { __token: t };
}

function emitNode(tree, depth) {
  const pad = '    '.repeat(depth);
  const lines = [];
  for (const [key, value] of Object.entries(tree)) {
    if (value.__token) {
      const t = value.__token;
      const { type, expr } = swiftValue(t);
      if (t.$description) lines.push(`${pad}/// ${t.$description}`);
      lines.push(`${pad}public static let ${swiftIdent(key)}: ${type} = ${expr}`);
    } else {
      lines.push(`${pad}public enum ${swiftEnumName(key)} {`);
      lines.push(...emitNode(value, depth + 1));
      lines.push(`${pad}}`);
    }
  }
  return lines;
}

await rm(SWIFT_DIR, { recursive: true, force: true });
await mkdir(SWIFT_DIR, { recursive: true });
for (const [file, { enum: enumName, tree }] of files) {
  const body = emitNode(tree, 2).join('\n');
  const src = `// ${HEADER}

import Foundation
import SwiftUI

extension ${config.swift.namespace} {
    public enum ${enumName} {
${body}
    }
}
`;
  await writeFile(path.join(SWIFT_DIR, file), src);
}

console.log(
  `tokens: ${lightTokens.length} resolved → dist/css/tokens.css, dist/json/tokens.json, ${files.size} Swift files`,
);
